import { Injectable } from '@angular/core';

@Injectable()
export class UsersAffilatedService {

  usersAffilatedData = [
    {
      compContactId: 1,
      persId: 1,
      firstname: 'Jerbi',
      lastname: 'Yasser',
      phone: '0711223344',
      email: 'SERVIMAX@CONTACT1.COM',
      compId: 1,
      name: 'SERVIMAX',
      phoneCompany: '7077777777',
      compTypeId: 1,
      compType: 'SERVIMAX',
    },
    {
      compContactId: 2,
      persId: 2,
      firstname: 'BELL CONTACT',
      lastname: 'CONTACT',
      phone: '0711223555',
      email: 'BELL@CONTACT1.COM',
      compId: 2,
      name: 'BELL TELECOM',
      phoneCompany: '7077777111',
      compTypeId: 2,
      compType: 'CLIENT',
    },
    {
    compContactId: 3,
    persId: 3,
    firstname: 'BANQUE NAT CONTACT',
    lastname: 'CONTACT',
    phone: '0711223666',
    email: 'BANQUENAT@CONTACT1.COM',
    compId: 3,
    name: 'BANQUE NATIONALE',
    phoneCompany: '7077777222',
    compTypeId: 2,
    compType: 'CLIENT',
    },
    {
    compContactId: 4,
    persId: 4,
    firstname: 'Saleh',
    lastname: 'Ben youcef',
    phone: '0711223777',
    email: 'AIRFRANCE@CONTACT1.COM',
    compId: 4,
    name: 'AIR FRANCE',
    phoneCompany: '7077777333',
    compTypeId: 2,
    compType: 'CLIENT',
    },
    {
    compContactId: 5,
    persId: 5,
    firstname: 'TUNIS BLEUE',
    lastname: 'AHMED',
    phone: '0711223244',
    email: 'TUNISBLEUE@CONTACT1.COM',
    compId: 5,
    name: 'RESTAURANT TUNIS LA BLEUE',
    phoneCompany: '7077778866',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
    {
    compContactId: 6,
    persId: 6,
    firstname: 'SOLEIL TUNIS',
    lastname: 'AHMED',
    phone: '0711223244',
    email: 'SOLEILTUNIS@CONTACT1.COM',
    compId: 6,
    name: 'RESTAURANT AU SOLEIL DE TUNIS',
    phoneCompany: '7077278866',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
    {
    compContactId: 7,
    persId: 7,
    firstname: 'COMPTOIRS CARTHAGE',
    lastname: 'ALI',
    phone: '0711223244',
    email: 'COMPTOIRS@CONTACT1.COM',
    compId: 7,
    name: 'LES COMPTOIRS DE CARTHAGE',
    phoneCompany: '7077278866',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
    {
    compContactId: 8,
    persId: 8,
    firstname: 'LA GOULETTE',
    lastname: 'HAMMADI',
    phone: '0721223244',
    email: 'GOULETTE@CONTACT1.COM',
    compId: 8,
    name: 'RESTAURANT LA GOULETTE',
    phoneCompany: '7077272466',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
    {
    compContactId: 9,
    persId: 13,
    firstname: 'YasserAff1',
    lastname: 'AFF1',
    phone: '0711223244',
    email: 'YASSER@AFF1.COM',
    compId: 9,
    name: 'RESTAURANT YASSER 1',
    phoneCompany: '7022778866',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
    {
    compContactId: 10,
    persId: 14,
    firstname: 'YasserAff2',
    lastname: 'AFF2',
    phone: '0711333244',
    email: 'YASSER@AFF2.COM',
    compId: 10,
    name: 'RESTAURANT YASSER 2',
    phoneCompany: '7022458866',
    compTypeId: 3,
    compType: 'AFFILIATED',
    },
];

/*      {
      account: 1,
      balance: 1500,
      userId: 5,
      username: 'belladmin',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 2,
      name: 'BELL TELECOM',
      },
      {
      account: 2,
      balance: 0,
      userId: 6,
      username: 'bncadmin',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 3,
      name: 'BANQUE NATIONALE',
      },
      {
      account: 3,
      balance: 0,
      userId: 7,
      username: 'airfradmin',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 4,
      name: 'AIR FRANCE',
      },
      {
      account: 4,
      balance: 349.531,
      userId: 8,
      username: 'rtlb',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 5,
      name: 'RESTAURANT TUNIS LA BLEUE',
      },
      {
      account: 5,
      balance: 47.326,
      userId: 9,
      username: 'rasdt',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 6,
      name: 'RESTAURANT AU SOLEIL DE TUNIS',
      },
      {
      account: 6,
      balance: 0,
      userId: 10,
      username: 'lcdc',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 7,
      name: 'LES COMPTOIRS DE CARTHAGE',
      },
      {
      account: 7,
      balance: 44.022,
      userId: 11,
      username: 'rlg',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 8,
      name: 'RESTAURANT LA GOULETTE',
      },
      {
      account: 12,
      balance: 102,
      userId: 16,
      username: 'yassaff1',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 9,
      name: 'RESTAURANT YASSER 1',
      },
      {
      account: 13,
      balance: 24.625,
      userId: 17,
      username: 'yassaff2',
      accounttypeId: 1,
      type: 'CORPO',
      compId: 10,
      name: 'RESTAURANT YASSER 2',
      },
      {
      account: 8,
      balance: 34.857,
      userId: 12,
      username: 'bellu1',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 2,
      name: 'BELL TELECOM',
      },
      {
      account: 9,
      balance: 0.428,
      userId: 13,
      username: 'bellu2',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 2,
      name: 'BELL TELECOM',
      },
      {
      account: 10,
      balance: 120.722,
      userId: 14,
      username: 'bellu3',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 2,
      name: 'BELL TELECOM',
      },
      {
      account: 11,
      balance: 19.923,
      userId: 15,
      username: 'bellu4',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 2,
      name: 'BELL TELECOM',
      },
      {
      account: 14,
      balance: 391.486,
      userId: 18,
      username: 'yass1',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 4,
      name: 'AIR FRANCE',
      },
      {
      account: 15,
      balance: 365.08,
      userId: 19,
      username: 'yass2',
      accounttypeId: 2,
      type: 'PERSONAL',
      compId: 4,
      name: 'AIR FRANCE',
    },*/

  getData(): Promise<any> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(this.usersAffilatedData);
      }, 1500);
    });
  }
}
